      - name: Fetch X posts and post
        env:
          DISCORD_WEBHOOK_URL_TRENDSPIDER: ${{ secrets.DISCORD_WEBHOOK_URL_TRENDSPIDER }}
          DISCORD_WEBHOOK_URL_COLE: ${{ secrets.DISCORD_WEBHOOK_URL_COLE }}
          DISCORD_WEBHOOK_URL_SPECUYCKY: ${{ secrets.DISCORD_WEBHOOK_URL_SPECUYCKY }}
        run: python x_tracker.py
